---
title: "Evaluate Batch"
author: ""
date: "`r Sys.Date()`"
output: 
  html_document:
    self_contained: TRUE
    code_folding: "hide"
    toc: true
    toc_float: true
    toc_collapsed: true
toc_depth: 3
number_sections: true
theme: lumen
editor_options:
  chunk_output_type: inline
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, dpi = 72, dev = "jpeg")
all_times <- list()  # store the time for each chunk
knitr::knit_hooks$set(time_it = local({
  now <- NULL
  function(before, options) {
    if (before) {
      now <<- Sys.time()
    } else {
      res <- difftime(Sys.time(), now)
      all_times[[options$label]] <<- round(lubridate::as.duration(res))
    }
  }
}))
knitr::opts_chunk$set(time_it = TRUE)
```
# Setup

load packages

```{r setup_env}
# logging
stdlog <- file(snakemake@log[["stdout"]], open="wt")
sink(stdlog, type = "output")
stderr <- file(snakemake@log[["stderr"]], open="wt")
sink(stderr, type = "message")

suppressPackageStartupMessages({
  library(SpatialExperiment)
  library(BiocParallel)
})
```



```{r}
sce <- readRDS(here::here(snakemake@input[["spe"]]))
#sce <- sce[,sample(seq_len(dim(sce)[2]),1000)]

cols_for_batch <- snakemake@params[["cols_for_batch"]]
cols_for_batch[cols_for_batch=="sample"] <- "sample_id"
stopifnot(all(cols_for_batch %in% colnames(colData(sce))))
```



```{r}
set.seed(123)
orderc <- sample(seq_along(colnames(sce)))
```

```{r plots_1, results='asis', fig.width=8, fig.height=8, warning=FALSE, message=FALSE}
for (colour_by in cols_for_batch) {
  uncor_colnam <- colnames(colData(sce))[stringr::str_detect(colnames(colData(sce)),paste0(colour_by,"_uncorrected"))]
  harmo_colnam <- colnames(colData(sce))[stringr::str_detect(colnames(colData(sce)),paste0(colour_by,"_harmony"))]
  message(paste0(uncor_colnam, collapse=" "))
  message(paste0(harmo_colnam, collapse=" "))
  message(paste0(colnames(colData(sce)), collapse=" "))
  message(paste0(reducedDimNames(sce), collapse=" "))
  message(colour_by)
  cat(paste0("\n\n# Batch: ",colour_by," {.tabset}\n\n"))
  cat("\n\n## UMAP uncorrected - color=cms\n\n")
  print(scater::plotReducedDim(sce[,orderc],"UMAP",colour_by = uncor_colnam[2]) + ggplot2::scale_color_viridis_c() + ggplot2::labs(colour=uncor_colnam[2]))
  cat("\n\n## UMAP corrected - color=cms\n\n")
  print(scater::plotReducedDim(sce[,orderc],"UMAP_harmony",colour_by = harmo_colnam[2]) + ggplot2::scale_color_viridis_c() + ggplot2::labs(colour=harmo_colnam[2]))
  cat(paste0("\n\n## UMAP uncorrected - color=",colour_by,"\n\n"))
  print(scater::plotReducedDim(sce[,orderc],"UMAP",colour_by = colour_by) + ggplot2::scale_color_viridis_d() + ggplot2::labs(colour=colour_by))
  cat(paste0("\n\n## UMAP corrected - color=",colour_by,"\n\n"))
  print(scater::plotReducedDim(sce[,orderc],"UMAP_harmony",colour_by = colour_by) + ggplot2::scale_color_viridis_d() + ggplot2::labs(colour=colour_by))
}
```


```{r plots_2, results='asis', fig.width=8, fig.height=8, warning=FALSE, message=FALSE}
cat(paste0("\n\n# Batch Histogram: {.tabset}\n\n"))
for (colour_by in cols_for_batch) {
  cat(paste0("\n\n## ",colour_by,"\n\n"))
  print(CellMixS::visHist(sce, metric=paste0("cms.",colour_by)))
}
```
