
# Filtering:
filtering:
    # threshold for filtering
    filter_thres: 0
    # type of filtering, possible types are:
    #   "below_threshold": All pixels below the set threshold are set to 0
    #   "all": the threshold value is subtracted from each pixel, subsequent negative values are set to 0
    filter_subtraction_type: "below_threshold"
    
segmentation:
    # list of nuclear channels used in segmentation, must exactly match names in summary_panels
    nuc_channels: ["DNA1","DNA2"]
    # list of membrane channels used in segmentation, must exactly match names in summary_panels
    mem_channels: ["HLA1"]
    # size of each pixel in micrometer
    image_pixelsize: 1.0
    # postprocessing parameters used in mesmer
    mesmer_postprocessing_paramsfile: "config/mesmer_postprocess_id01.yml"

## steinbock, which version is used
steinbock_container: "docker://ghcr.io/bodenmillergroup/steinbock:0.13.4"

## additional metadata of channels, expects two columns:
#    'channel' (name of channel) and 
#    'type' (either 'state' for cell state marker, 'type' for cell type marker, or something else)
channel_metadata_file: "config/channel_metadata.csv"

## Cell level filtering
# minimum cell area
min_cell_area: 10
