
# Filtering:
filtering:
    # threshold for filtering
    filter_thres: 1.5
    kernelsize: 21
    # type of filtering, possible types are:
    #   "below_threshold": All pixels below the set threshold are set to 0
    #   "all": the threshold value is subtracted from each pixel, subsequent negative values are set to 0
    filter_subtraction_type: "below_threshold"
    
segmentation:
    # list of nuclear channels used in segmentation, must exactly match names in summary_panels
    nuc_channels: ["DNA1","DNA2"]
    # list of membrane channels used in segmentation, must exactly match names in summary_panels
    mem_channels: ["Seg1","Seg2","Seg3"]
    # size of each pixel in micrometer
    image_pixelsize: 1.0
    # postprocessing parameters used in mesmer
    mesmer_postprocessing_paramsfile: "config/mesmer_postprocess_id01.yml"

## steinbock, which version is used
steinbock_container: "docker://ghcr.io/bodenmillergroup/steinbock:0.13.4"

## additional metadata of channels, expects two columns:
#    'channel' (name of channel) and 
#    'type' (either 'state' for cell state marker, 'type' for cell type marker, or something else)
channel_metadata_file: "config/channel_metadata.csv"

## Cell level filtering
# minimum cell area
min_cell_area: 10

## Sample metadata csv
# one column has to have name 'sample'
sample_metadata: "config/sample_metadata.csv"
# colnames in 'sample_metadata' that are used for batch correction
cols_for_batch: ["sample","slide"]

## cell mixing score number of neighbors
k_cms: 500


## Annotation 
# name of the clustering used for annotation
clustering_used: "leiden_k20_res0.15"
# name of the csv file containing annotation labels, two columns are expected:
#   "cluster": the cluster number (corresponding to the clusters in "clustering_used" parameter)
#   "celltype": name of the cluster
clustering_annotation_file: "config/clustering_annotation_file.csv"

